type LinkItem = { title: string; url: string };
type Bookmark = { title: string; url: string; createdAt: string };
type HistoryItem = { title: string; url: string; visitedAt: string };
type IndexedDocument = { title: string; url: string; text: string; headings: string[]; links: LinkItem[]; indexedAt: string };
type GraphDocument = { title: string; url: string; indexedAt: string; links: LinkItem[] };
type Note = { id: number; quote: string; body: string; tags: string[]; sourceUrl: string; sourceTitle: string; createdAt: string };
type GraphData = { documents: GraphDocument[]; notes: Note[] };
type SearchResult = { kind: "document"; title: string; url: string; headings: string[]; indexedAt: string } | { kind: "note"; id: number; title: string; url: string; quote: string; body: string; tags: string[]; indexedAt: string };
type BrowserStore = { load(): Promise<{ bookmarks: Bookmark[]; history: HistoryItem[] }>; toggleBookmark(item: Bookmark): Promise<Bookmark[]>; addHistory(item: HistoryItem): Promise<HistoryItem[]>; indexDocument(item: IndexedDocument): Promise<number>; documentCount(): Promise<number>; graph(): Promise<GraphData>; search(query: string): Promise<{ results: SearchResult[]; error?: string }>; notes(): Promise<Note[]>; saveNote(note: Omit<Note, "id" | "createdAt">): Promise<Note>; updateNote(note: Pick<Note, "id" | "body" | "tags">): Promise<Note>; deleteNote(id: number): Promise<void> };
declare global { interface Window { browserStore: BrowserStore } }

type Tab = { id: number; title: string; url: string; view: Electron.WebviewTag; headings?: Array<{ level: string; text: string }>; links?: LinkItem[]; pendingQuote?: string };
const tabs: Tab[] = []; let activeId = 0; let nextId = 1; let bookmarks: Bookmark[] = []; let history: HistoryItem[] = []; let panel = "structure"; let editingNote: Note | undefined; let activeTag = "";
const byId = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const tabsEl = byId<HTMLDivElement>("tabs"), views = byId<HTMLDivElement>("views"), address = byId<HTMLInputElement>("address"), empty = byId<HTMLDivElement>("empty"), content = byId<HTMLDivElement>("panel-content");
const noteDialog = byId<HTMLDialogElement>("note-dialog"), noteQuote = byId<HTMLElement>("note-quote"), noteBody = byId<HTMLTextAreaElement>("note-body"), noteTags = byId<HTMLInputElement>("note-tags");
const current = () => tabs.find((tab) => tab.id === activeId);
const normalizeUrl = (input: string) => { const text = input.trim(); if (/^https?:\/\//i.test(text)) return text; if (/^[\w-]+(\.[\w-]+)+/.test(text)) return `https://${text}`; return `https://www.google.com/search?q=${encodeURIComponent(text)}`; };
const escapeHtml = (value: string) => { const node = document.createElement("div"); node.textContent = value; return node.innerHTML; };

function addTab(url = "", title = "새 탭") {
  const id = nextId++; const view = document.createElement("webview") as Electron.WebviewTag;
  view.partition = "persist:atlas"; view.setAttribute("allowpopups", "true"); view.className = "browser-view"; view.src = url || "about:blank"; views.append(view);
  const tab: Tab = { id, title, url, view }; tabs.push(tab);
  view.addEventListener("did-navigate", () => pageChanged(tab)); view.addEventListener("did-navigate-in-page", () => pageChanged(tab));
  view.addEventListener("page-title-updated", (event) => { tab.title = event.title || tab.url; renderTabs(); });
  view.addEventListener("did-start-loading", () => setStatus("LOADING PAGE")); view.addEventListener("did-stop-loading", () => { setStatus("PAGE READY"); if (tab.pendingQuote) { tab.view.findInPage(tab.pendingQuote); tab.pendingQuote = undefined; } inspectPage(tab); });
  view.addEventListener("new-window", (event) => addTab((event as unknown as { url: string }).url)); activate(id);
}
function pageChanged(tab: Tab) { tab.url = tab.view.getURL(); address.value = tab.url; renderTabs(); updateBookmark(); if (tab.url && !tab.url.startsWith("about:")) window.browserStore.addHistory({ title: tab.title, url: tab.url, visitedAt: new Date().toISOString() }).then((items) => { history = items; if (panel === "history") renderPanel(); }); }
function activate(id: number) { activeId = id; empty.classList.toggle("hidden", tabs.length > 0); views.classList.toggle("visible", tabs.length > 0); tabs.forEach((tab) => tab.view.classList.toggle("active", tab.id === id)); address.value = current()?.url || ""; renderTabs(); updateBookmark(); renderPanel(); }
function closeTab(id: number) { const index = tabs.findIndex((tab) => tab.id === id); if (index < 0) return; tabs[index].view.remove(); tabs.splice(index, 1); if (activeId === id) tabs.length ? activate(tabs[Math.max(0, index - 1)].id) : activate(0); else renderTabs(); }
function renderTabs() { tabsEl.innerHTML = ""; tabs.forEach((tab) => { const item = document.createElement("button"); item.className = `tab ${tab.id === activeId ? "active" : ""}`; item.innerHTML = `<span class="favicon">◆</span><span class="tab-title">${escapeHtml(tab.title || "새 탭")}</span><span class="close">×</span>`; item.onclick = (event) => (event.target as HTMLElement).classList.contains("close") ? closeTab(tab.id) : activate(tab.id); tabsEl.append(item); }); }
function setStatus(value: string) { byId("status").innerHTML = `<i></i> ${value}`; }
function updateBookmark() { const tab = current(); const selected = !!tab && bookmarks.some((item) => item.url === tab.url); byId("bookmark").classList.toggle("bookmarked", selected); byId("bookmark").textContent = selected ? "★" : "☆"; }
async function inspectPage(tab: Tab) {
  if (tab.url.startsWith("about:")) return;
  try {
    const data = await tab.view.executeJavaScript(`(() => ({headings:Array.from(document.querySelectorAll('h1,h2,h3')).slice(0,35).map(n=>({level:n.tagName,text:(n.innerText||'').trim()})).filter(n=>n.text),links:Array.from(document.querySelectorAll('a[href]')).slice(0,40).map(a=>({title:(a.innerText||a.getAttribute('aria-label')||a.href).trim().slice(0,90),url:a.href})).filter(a=>a.title&&a.url.startsWith('http')),text:(document.body?.innerText||'').replace(/\\s+/g,' ').slice(0,12000)}))()`);
    tab.headings = data.headings; tab.links = data.links;
    const count = await window.browserStore.indexDocument({ title: tab.title, url: tab.url, text: data.text, headings: data.headings.map((item: { text: string }) => item.text), links: data.links, indexedAt: new Date().toISOString() });
    byId("page-info").textContent = `${count} DOCUMENTS INDEXED`;
    if (tab.id === activeId && (panel === "structure" || panel === "graph" || panel === "search")) renderPanel();
  } catch { setStatus("PAGE READY · STRUCTURE UNAVAILABLE"); }
}
function graphLabel(value: string) { return value.replace(/^https?:\/\//, "").replace(/^www\./, "").slice(0, 22); }
function openNoteDialog(note?: Note) { editingNote = note; byId("note-mode").textContent = note ? "REFINE A THOUGHT" : "CAPTURE A THOUGHT"; noteQuote.textContent = note?.quote || ""; noteBody.value = note?.body || ""; noteTags.value = note?.tags.join(", ") || ""; byId("delete-note").classList.toggle("visible", !!note); noteDialog.showModal(); }
function renderGraph(data: GraphData, activeUrl?: string) {
  const { documents, notes } = data;
  const nodes = new Map<string, { title: string; url: string; kind: string }>();
  documents.forEach((document) => nodes.set(document.url, { title: document.title, url: document.url, kind: document.url === activeUrl ? "current" : "source" }));
  const edges = documents.flatMap((document) => document.links.filter((link) => nodes.has(link.url) || document.url === activeUrl).slice(0, 12).map((link) => {
    if (!nodes.has(link.url)) nodes.set(link.url, { title: link.title, url: link.url, kind: "target" });
    return { source: document.url, target: link.url };
  })).slice(0, 45);
  const values = [...nodes.values()].slice(0, 22); const noteNodes = notes.slice(0, 10).map((note) => ({ title: note.quote, url: `note:${note.id}`, kind: "note", sourceUrl: note.sourceUrl }));
  const allNodes = [...values, ...noteNodes]; const positions = new Map(allNodes.map((node, index) => {
    const angle = (Math.PI * 2 * index) / Math.max(values.length, 1) - Math.PI / 2;
    const radius = index === 0 ? 0 : 70 + (index % 3) * 17;
    return [node.url, { x: 130 + Math.cos(angle) * radius, y: 115 + Math.sin(angle) * radius }];
  }));
  const position = (url: string) => positions.get(url) || { x: 130, y: 115 };
  const noteEdges = noteNodes.filter((note) => positions.has(note.sourceUrl)).map((note) => ({ source: note.sourceUrl, target: note.url }));
  const edgeMarkup = [...edges, ...noteEdges].filter((edge) => positions.has(edge.source) && positions.has(edge.target)).map((edge) => `<line class="graph-edge" x1="${position(edge.source).x}" y1="${position(edge.source).y}" x2="${position(edge.target).x}" y2="${position(edge.target).y}" />`).join("");
  const nodeMarkup = allNodes.map((node) => { const point = position(node.url); const noteId = node.url.startsWith("note:") ? node.url.slice(5) : ""; const shape = node.kind === "note" ? `<rect class="graph-node note" x="${point.x - 5}" y="${point.y - 5}" width="10" height="10" />` : `<circle class="graph-node ${node.kind}" cx="${point.x}" cy="${point.y}" r="${node.kind === "current" ? 8 : 6}" />`; return `<g data-url="${encodeURIComponent(node.url)}" data-note-id="${noteId}">${shape}<text class="graph-label" x="${point.x + 9}" y="${point.y + 3}">${escapeHtml(graphLabel(node.title || node.url))}</text></g>`; }).join("");
  return `<svg class="graph-canvas" viewBox="0 0 260 230" role="img" aria-label="문서 링크 그래프">${edgeMarkup}${nodeMarkup}</svg>`;
}
function renderPanel() {
  const tab = current(); document.querySelectorAll(".side-item").forEach((item) => item.classList.toggle("active", (item as HTMLElement).dataset.panel === panel));
  if (panel === "structure") { const headings = tab?.headings || []; content.innerHTML = headings.length ? headings.map((item, index) => `<button class="outline-item" data-index="${index}" data-level="${item.level}">${escapeHtml(item.text)}</button>`).join("") : `<p class="help">페이지를 열면 문서의 제목 구조가 여기에 표시됩니다.</p>`; content.querySelectorAll<HTMLElement>(".outline-item").forEach((item) => item.onclick = () => tab?.view.executeJavaScript(`document.querySelectorAll('h1,h2,h3')[${item.dataset.index}]?.scrollIntoView({behavior:'smooth'})`)); }
  if (panel === "graph") { content.innerHTML = `<p class="help graph-help">원형은 문서, 사각형은 원문에 연결된 노트입니다.</p><div id="graph-view"><p class="help">링크 관계를 불러오는 중입니다.</p></div>`; window.browserStore.graph().then((data) => { if (panel !== "graph") return; const graph = byId("graph-view"); graph.innerHTML = data.documents.length ? renderGraph(data, tab?.url) : `<p class="help">문서를 방문하면 지식 그래프가 표시됩니다.</p>`; graph.querySelectorAll<HTMLElement>("g[data-url]").forEach((item) => item.onclick = () => { const noteId = item.dataset.noteId; if (noteId) { panel = "notes"; renderPanel(); return; } navigate(decodeURIComponent(item.dataset.url || "")); }); }); }
  if (panel === "search") { content.innerHTML = `<form id="local-search"><input id="local-query" placeholder="AI AND 논문 NOT 광고" /><button>찾기</button></form><p class="help">SQLite FTS5 문서와 지식 노트를 함께 검색합니다.<br>AND · OR · NOT · 괄호 · "구문 검색" 지원</p><div id="search-results"></div>`; byId<HTMLFormElement>("local-search").onsubmit = async (event) => { event.preventDefault(); const query = byId<HTMLInputElement>("local-query").value.trim(); const response = await window.browserStore.search(query); const target = byId("search-results"); const list = response.results.map((result) => result.kind === "note" ? `<button class="note-card" data-url="${encodeURIComponent(result.url)}" data-quote="${encodeURIComponent(result.quote)}"><b>NOTE · ${escapeHtml(result.title)}</b><q>${escapeHtml(result.quote)}</q><span class="note-tags">${escapeHtml(result.tags.map((tag) => `#${tag}`).join(" "))}</span></button>` : `<button class="saved" data-url="${encodeURIComponent(result.url)}"><b>${escapeHtml(result.title)}</b><span>${escapeHtml(result.url)}</span></button>`).join(""); target.innerHTML = response.error ? `<p class="help">${escapeHtml(response.error)}</p>` : `<p class="help">${response.results.length}개의 결과</p>${list || '<p class="help">일치하는 색인 문서가 없습니다.</p>'}`; target.querySelectorAll<HTMLElement>("[data-url]").forEach((item) => item.onclick = () => navigate(decodeURIComponent(item.dataset.url || ""))); }; }
  if (panel === "notes") { content.innerHTML = `<p class="help">카드를 눌러 메모와 태그를 편집하세요.</p><div id="note-filter"></div><div id="note-list"><p class="help">노트를 불러오는 중입니다.</p></div>`; window.browserStore.notes().then((notes) => { if (panel !== "notes") return; const tags = [...new Set(notes.flatMap((note) => note.tags))]; if (activeTag && !tags.includes(activeTag)) activeTag = ""; const filters = byId("note-filter"); filters.innerHTML = tags.length ? `<button class="tag-filter ${activeTag ? "" : "active"}" data-tag="">ALL ${notes.length}</button>${tags.map((tag) => `<button class="tag-filter ${tag === activeTag ? "active" : ""}" data-tag="${encodeURIComponent(tag)}">#${escapeHtml(tag)}</button>`).join("")}` : ""; filters.querySelectorAll<HTMLElement>(".tag-filter").forEach((item) => item.onclick = () => { activeTag = decodeURIComponent(item.dataset.tag || ""); renderPanel(); }); const visibleNotes = activeTag ? notes.filter((note) => note.tags.includes(activeTag)) : notes; const list = byId("note-list"); list.innerHTML = visibleNotes.length ? visibleNotes.map((note) => `<button class="note-card" data-id="${note.id}"><b>${escapeHtml(note.sourceTitle)}</b><q>${escapeHtml(note.quote)}</q>${note.body ? `<span>${escapeHtml(note.body.slice(0, 110))}</span>` : ""}<span class="note-tags">${escapeHtml(note.tags.map((tag) => `#${tag}`).join(" "))}</span></button>`).join("") : `<p class="help">${activeTag ? `#${escapeHtml(activeTag)} 태그의 노트가 없습니다.` : "저장된 지식 노트가 없습니다."}</p>`; list.querySelectorAll<HTMLElement>(".note-card").forEach((item) => item.onclick = () => openNoteDialog(notes.find((note) => note.id === Number(item.dataset.id)))); }); }
  if (panel === "bookmarks") content.innerHTML = bookmarks.length ? bookmarks.map((item) => `<button class="saved" data-url="${encodeURIComponent(item.url)}"><b>${escapeHtml(item.title)}</b><span>${escapeHtml(item.url)}</span></button>`).join("") : `<p class="help">별표를 눌러 현재 페이지를 저장하세요.</p>`;
  if (panel === "history") content.innerHTML = history.length ? history.slice(0, 20).map((item) => `<button class="saved" data-url="${encodeURIComponent(item.url)}"><b>${escapeHtml(item.title)}</b><span>${escapeHtml(item.url)}</span></button>`).join("") : `<p class="help">아직 탐색한 페이지가 없습니다.</p>`;
  content.querySelectorAll<HTMLElement>(".saved").forEach((item) => item.onclick = () => navigate(decodeURIComponent(item.dataset.url || "")));
}
function navigate(url: string) { const tab = current(); if (!tab) { addTab(normalizeUrl(url)); return; } tab.view.loadURL(normalizeUrl(url)); }
byId<HTMLFormElement>("address-form").addEventListener("submit", (event) => { event.preventDefault(); navigate(address.value); }); byId("new-tab").onclick = () => addTab(); byId("back").onclick = () => current()?.view.goBack(); byId("forward").onclick = () => current()?.view.goForward(); byId("reload").onclick = () => current()?.view.reload();
byId("bookmark").onclick = async () => { const tab = current(); if (!tab?.url || tab.url.startsWith("about:")) return; bookmarks = await window.browserStore.toggleBookmark({ title: tab.title, url: tab.url, createdAt: new Date().toISOString() }); updateBookmark(); if (panel === "bookmarks") renderPanel(); };
byId("add-note").onclick = async () => { const tab = current(); if (!tab || tab.url.startsWith("about:")) return; try { const quote = await tab.view.executeJavaScript("window.getSelection()?.toString().trim() || ''") as string; if (!quote) { setStatus("SELECT TEXT TO CREATE A NOTE"); return; } openNoteDialog({ id: 0, quote: quote.slice(0, 3000), body: "", tags: [], sourceUrl: tab.url, sourceTitle: tab.title, createdAt: "" }); editingNote = undefined; byId("delete-note").classList.remove("visible"); } catch { setStatus("NOTE CAPTURE UNAVAILABLE"); } };
byId("close-note").onclick = () => noteDialog.close();
byId<HTMLFormElement>("note-form").onsubmit = async (event) => { event.preventDefault(); const tab = current(); const quote = noteQuote.textContent || ""; if (!quote) return; if (editingNote) await window.browserStore.updateNote({ id: editingNote.id, body: noteBody.value, tags: noteTags.value.split(",") }); else if (tab) await window.browserStore.saveNote({ quote, body: noteBody.value, tags: noteTags.value.split(","), sourceUrl: tab.url, sourceTitle: tab.title }); noteDialog.close(); setStatus(editingNote ? "KNOWLEDGE NOTE UPDATED" : "KNOWLEDGE NOTE SAVED"); editingNote = undefined; if (panel === "notes" || panel === "graph") renderPanel(); };
byId("delete-note").onclick = async () => { if (!editingNote) return; await window.browserStore.deleteNote(editingNote.id); noteDialog.close(); editingNote = undefined; setStatus("KNOWLEDGE NOTE DELETED"); if (panel === "notes" || panel === "graph") renderPanel(); };
document.querySelectorAll<HTMLElement>(".side-item").forEach((item) => item.onclick = () => { panel = item.dataset.panel || "structure"; renderPanel(); }); document.addEventListener("keydown", (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "l") { event.preventDefault(); address.focus(); address.select(); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "t") { event.preventDefault(); addTab(); } });
window.browserStore.load().then(async (state) => { bookmarks = state.bookmarks; history = state.history; byId("page-info").textContent = `${await window.browserStore.documentCount()} DOCUMENTS INDEXED`; renderPanel(); }); renderPanel();
